import { type NextPage } from "next";
import Head from "next/head";

import { requireAuth } from "../../utils/requireAuth";
import BooksTable from "../../components/BooksTable";

export const getServerSideProps = requireAuth(async (ctx) => {
    return { props: {} }
}, 'books');

const Books: NextPage = () => {
    return (
        <>
            <Head>
                <title>Rekindled</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className="text-4xl font-bold mt-10">Books</h1>
                <div className="flex flex-col">
                    <BooksTable columns={[{ Header: 'Title', accessor: 'title' }, { Header: 'Author', accessor: 'author' }]} data={[{ title: 'The Hobbit', author: 'J.R.R. Tolkien' }, { title: 'The Fellowship of the Ring', author: 'J.R.R. Tolkien' }]} />
                </div>
            </main>
        </>
    );
};

export default Books;
