import { type NextPage } from "next";
import Head from "next/head";

import { requireAuth } from "../../../utils/requireAuth";
import QuoteTile from "../../../components/QuoteTile";
import Link from "next/link";

export const getServerSideProps = requireAuth(async (ctx) => {
    return { props: {} }
}, 'books');

const BookReview: NextPage = () => {
    return (
        <>
            <Head>
                <title>Rekindled</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col justify-center items-center gap-4">
                <h1 className="text-4xl font-bold mt-10">Your next five moves</h1>
                <div className="flex flex-col gap-y-4">
                    <QuoteTile quote="The world is full of magic things, patiently waiting for our senses to grow sharper." location="Winnie the Pooh" />
                    <QuoteTile quote="The world is full of magic things, patiently waiting for our senses to grow sharper." location="Winnie the Pooh" />
                </div>
                <Link className="bg-red-500 text-white px-4 py-2 rounded-lg" href={"/books"}>Back</Link>
            </main>
        </>
    );
};

export default BookReview;
