import { type NextPage } from "next";
import Head from "next/head";

import { requireAuth } from "../../../utils/requireAuth";
import QuoteTile from "../../../components/QuoteTile";
import Link from "next/link";
import { prisma } from "../../../server/db";
import { Highlight } from "@prisma/client";
import { getSession } from "next-auth/react";

export const getServerSideProps = requireAuth(async (ctx) => {
    const session = await getSession({ ctx });
    const book = await prisma.book.findUnique({
        where: {
            id: ctx.query.bookid as string
        },
        include: {
            highlights: true
        }
    });
    if (book?.userId !== session?.user.id) {
        return {
            notFound: true
        }
    }
    return {
        props: {
            highlights: book?.highlights
        }
    }
}, 'books');

type Props = {
    highlights: Highlight[];
}

const BookReview: NextPage<Props> = ({ highlights }) => {
    return (
        <>
            <Head>
                <title>Rekindled</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col justify-center items-center gap-4">
                <h1 className="text-4xl font-bold">Your next five moves</h1>
                <div className="flex flex-col gap-y-4">
                    {
                        highlights.length > 0
                            ? highlights.map((highlight) => <QuoteTile key={highlight.id} quote={highlight.content} location={highlight.location} />)
                            : <p className="text-gray-500">No highlights found</p>
                    }
                </div>
                <Link className="bg-red-500 text-white px-4 py-2 rounded-lg" href={"/books"}>Back</Link>
            </main>
        </>
    );
};

export default BookReview;
