import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";
import { ArrowUpOnSquareIcon, BuildingLibraryIcon, InboxArrowDownIcon } from '@heroicons/react/24/outline'

import IconTile from "../components/IconTile";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const { push } = useRouter();
  const onGetStarted = () => {
    if (sessionData?.user !== undefined) {
      push('/books');
    } else {
      signIn(undefined, { callbackUrl: `${window.location.origin}/books` });
    }
  }
  return (
    <>
      <Head>
        <title>Rekindled</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center gap-10 h-full w-full flex-1">
        <div className="flex flex-col max-w-5xl items-center justify-center text-center">
          <h1 className="text-5xl sm:text-6xl font-bold text-red-500 p-2">Rekindle your highlights, daily.</h1>
          <h2 className="text-lg sm:text-xl text-gray-600 font-semibold max-w-2xl">
            A daily email with a collection of quotes from your Kindle highlights. Never forget a great quote again.
          </h2>
        </div>
        <button
          type='button'
          className="w-52 bg-red-500 text-white font-bold py-2 px-4 rounded-full duration-200 ease-in-out transform hover:scale-110 hover:bg-red-600"
          onClick={onGetStarted}>Get Started</button>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <IconTile icon={<InboxArrowDownIcon className='w-14 h-14 text-red-500' />} title='A daily email' description="With curated quotes for the day from your kindle highlights." />
          <IconTile icon={<ArrowUpOnSquareIcon className='w-14 h-14 text-red-500' />} title='Connect via file import' description="Our online service allows manual file imports via your kindle." />
          <IconTile icon={<BuildingLibraryIcon className='w-14 h-14 text-red-500' />} title='Remember your highlights' description="Remember what you read and rekindle your highlights." />

        </div>
      </main>
    </>
  );
};

export default Home;
