import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ArrowPathIcon } from "@heroicons/react/24/outline";

import { requireAuth } from "../utils/requireAuth";
import { getSession } from "next-auth/react";
import dayjs from "dayjs";
import { prisma } from "../server/db";
import FileUploadModal from "../components/FileUploadModal";
import { useState } from "react";

export const getServerSideProps = requireAuth(async (ctx) => {
    const session = await getSession({ ctx });
    const latestImport = await prisma.import.findFirst({
        where: {
            userId: session?.user?.id
        },
        orderBy: {
            importedOn: 'desc'
        },
        select: {
            importedOn: true
        }
    });
    return {
        props: {
            lastImportedOn: latestImport?.importedOn.toString() ?? null
        }
    }
}, '/sync');


type Props = {
    lastImportedOn: string | null;
}

const Sync: NextPage<Props> = ({ lastImportedOn }) => {
    const [showFileUploadModal, setShowFileUploadModal] = useState(false);
    const openFileUploadModal = () => setShowFileUploadModal(true);
    const closeFileUploadModal = () => setShowFileUploadModal(false);
    return (
        <>
            <Head>
                <title>Rekindled</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className="text-4xl font-bold mb-5 text-red-500">Import Highlights</h1>
                <div className="flex flex-col sm:flex-row gap-4">
                    <div className="border rounded-lg h-56 w-full sm:w-64 flex flex-col px-4">
                        <Image src="/kindle-icon.png" alt="Kindle" width={50} height={50} className="rounded-lg mt-5" />
                        <div className="flex-1">
                            <h1 className='text-xl text-gray-700 mt-2'>Kindle - Upload</h1>
                            <span className='text-xs text-gray-600'>Import your books from Kindle file upload</span>
                        </div>
                        <div className="flex flex-row pb-2 mt-2">
                            <div className="flex flex-row gap-1 text-xs flex-1 w-full">
                                <ArrowPathIcon className="w-4 h-4 text-red-500" />
                                <span className="text-[0.6rem] text-gray-500">Last updated {lastImportedOn !== null
                                    ? dayjs(lastImportedOn).format("DD/MM/YYYY")
                                    : 'never'}</span>
                            </div>
                            <button
                                className="bg-white border border-red-500 text-red-500 px-3 rounded-lg hover:bg-red-500 hover:text-white duration-200 h-6 text-xs self-end mt-[-5px]"
                                onClick={openFileUploadModal}>Sync</button>
                        </div>
                    </div>
                </div>
                <FileUploadModal isOpen={showFileUploadModal} closeModal={closeFileUploadModal} />
            </main>
        </>
    );
};

export default Sync;
