name: daily-email-cron
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Send daily emails via api call
        run: |
          curl --request POST \
          --url '${{ secrets.API_URL }}' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
